// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

package system;

@net.sf.jni4net.attributes.ClrType
public abstract class EventHandler extends system.MulticastDelegate {
    
    //<generated-proxy>
    private static system.Type staticType;
    
    protected EventHandler(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    protected EventHandler() {
            super(((net.sf.jni4net.inj.INJEnv)(null)), 0);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Object;LSystem/EventArgs;)V")
    public abstract void Invoke(system.Object sender, system.EventArgs e);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Object;LSystem/EventArgs;LSystem/AsyncCallback;LSystem/Object;)LSystem/IAsyncResult;")
    public system.IAsyncResult BeginInvoke(system.Object sender, system.EventArgs e, system.AsyncCallback callback, system.Object object) {
        throw new system.NotImplementedException();
    }
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/IAsyncResult;)V")
    public void EndInvoke(system.IAsyncResult result) {
        throw new system.NotImplementedException();
    }
    
    public static system.Type typeof() {
        return system.EventHandler.staticType;
    }
    
    private static void InitJNI(net.sf.jni4net.inj.INJEnv env, system.Type staticType) {
        system.EventHandler.staticType = staticType;
    }
    //</generated-proxy>
}

//<generated-proxy>
@net.sf.jni4net.attributes.ClrProxy
class __EventHandler extends system.EventHandler {
    
    protected __EventHandler(net.sf.jni4net.inj.INJEnv __env, long __handle) {
            super(__env, __handle);
    }
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Object;LSystem/EventArgs;)V")
    public native void Invoke(system.Object sender, system.EventArgs e);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/Object;LSystem/EventArgs;LSystem/AsyncCallback;LSystem/Object;)LSystem/IAsyncResult;")
    public native system.IAsyncResult BeginInvoke(system.Object sender, system.EventArgs e, system.AsyncCallback callback, system.Object object);
    
    @net.sf.jni4net.attributes.ClrMethod("(LSystem/IAsyncResult;)V")
    public native void EndInvoke(system.IAsyncResult result);
}
//</generated-proxy>
