//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by jni4net. See http://jni4net.sourceforge.net/ 
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace System.Collections {
    
    
    #region Component Designer generated code 
    public partial class ArrayList_ {
        
        public static global::java.lang.Class _class {
            get {
                return global::System.Collections.@__ArrayList.staticClass;
            }
        }
    }
    #endregion
    
    #region Component Designer generated code 
    [global::net.sf.jni4net.attributes.JavaProxyAttribute(typeof(global::System.Collections.ArrayList), typeof(global::System.Collections.ArrayList_))]
    [global::net.sf.jni4net.attributes.ClrWrapperAttribute(typeof(global::System.Collections.ArrayList), typeof(global::System.Collections.ArrayList_))]
    internal sealed partial class @__ArrayList : global::java.lang.Object {
        
        internal new static global::java.lang.Class staticClass;
        
        private @__ArrayList(global::net.sf.jni4net.jni.JNIEnv @__env) : 
                base(@__env) {
        }
        
        private static void InitJNI(global::net.sf.jni4net.jni.JNIEnv @__env, java.lang.Class @__class) {
            global::System.Collections.@__ArrayList.staticClass = @__class;
        }
        
        private static global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> @__Init(global::net.sf.jni4net.jni.JNIEnv @__env, global::java.lang.Class @__class) {
            global::System.Type @__type = typeof(__ArrayList);
            global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod> methods = new global::System.Collections.Generic.List<global::net.sf.jni4net.jni.JNINativeMethod>();
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "GetEnumerator", "GetEnumerator0", "()Lsystem/collections/IEnumerator;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "CopyTo", "CopyTo1", "(Lsystem/Array;I)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getCount", "Count2", "()I"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getSyncRoot", "SyncRoot3", "()Lsystem/Object;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "isSynchronized", "IsSynchronized4", "()Z"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getItem", "Item5", "(I)Lsystem/Object;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setItem", "Item6", "(ILsystem/Object;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Add", "Add7", "(Lsystem/Object;)I"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Contains", "Contains8", "(Lsystem/Object;)Z"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Clear", "Clear9", "()V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "isReadOnly", "IsReadOnly10", "()Z"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "isFixedSize", "IsFixedSize11", "()Z"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "IndexOf", "IndexOf12", "(Lsystem/Object;)I"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Insert", "Insert13", "(ILsystem/Object;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Remove", "Remove14", "(Lsystem/Object;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "RemoveAt", "RemoveAt15", "(I)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Clone", "Clone16", "()Lsystem/Object;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "getCapacity", "Capacity17", "()I"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "setCapacity", "Capacity18", "(I)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Adapter", "Adapter19", "(Lsystem/collections/IList;)Lsystem/collections/ArrayList;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "AddRange", "AddRange20", "(Lsystem/collections/ICollection;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "BinarySearch", "BinarySearch21", "(IILsystem/Object;Lsystem/Object;)I"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "BinarySearch", "BinarySearch22", "(Lsystem/Object;)I"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "BinarySearch", "BinarySearch23", "(Lsystem/Object;Lsystem/Object;)I"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "CopyTo", "CopyTo24", "(Lsystem/Array;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "CopyTo", "CopyTo25", "(ILsystem/Array;II)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "FixedSize", "FixedSize26", "(Lsystem/collections/IList;)Lsystem/collections/IList;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "FixedSize", "FixedSize27", "(Lsystem/collections/ArrayList;)Lsystem/collections/ArrayList;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "GetEnumerator", "GetEnumerator28", "(II)Lsystem/collections/IEnumerator;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "IndexOf", "IndexOf29", "(Lsystem/Object;I)I"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "IndexOf", "IndexOf30", "(Lsystem/Object;II)I"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "InsertRange", "InsertRange31", "(ILsystem/collections/ICollection;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "LastIndexOf", "LastIndexOf32", "(Lsystem/Object;)I"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "LastIndexOf", "LastIndexOf33", "(Lsystem/Object;I)I"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "LastIndexOf", "LastIndexOf34", "(Lsystem/Object;II)I"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "ReadOnly", "ReadOnly35", "(Lsystem/collections/IList;)Lsystem/collections/IList;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "ReadOnly", "ReadOnly36", "(Lsystem/collections/ArrayList;)Lsystem/collections/ArrayList;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "RemoveRange", "RemoveRange37", "(II)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Repeat", "Repeat38", "(Lsystem/Object;I)Lsystem/collections/ArrayList;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Reverse", "Reverse39", "()V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Reverse", "Reverse40", "(II)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "SetRange", "SetRange41", "(ILsystem/collections/ICollection;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "GetRange", "GetRange42", "(II)Lsystem/collections/ArrayList;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Sort", "Sort43", "()V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Sort", "Sort44", "(Lsystem/Object;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Sort", "Sort45", "(IILsystem/Object;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Synchronized", "Synchronized46", "(Lsystem/collections/IList;)Lsystem/collections/IList;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "Synchronized", "Synchronized47", "(Lsystem/collections/ArrayList;)Lsystem/collections/ArrayList;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "ToArray", "ToArray48", "()[Lsystem/Object;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "ToArray", "ToArray49", "(Lsystem/Type;)Lsystem/Array;"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "TrimToSize", "TrimToSize50", "()V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorArrayList0", "__ctorArrayList0", "(Lnet/sf/jni4net/inj/IClrProxy;)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorArrayList1", "__ctorArrayList1", "(Lnet/sf/jni4net/inj/IClrProxy;I)V"));
            methods.Add(global::net.sf.jni4net.jni.JNINativeMethod.Create(@__type, "__ctorArrayList2", "__ctorArrayList2", "(Lnet/sf/jni4net/inj/IClrProxy;Lsystem/collections/ICollection;)V"));
            return methods;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle GetEnumerator0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Lsystem/collections/IEnumerator;
            // ()LSystem/Collections/IEnumerator;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::System.Collections.ArrayList @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Collections.ArrayList>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<global::System.Collections.IEnumerator>(@__env, ((global::System.Collections.IEnumerable)(@__real)).GetEnumerator());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void CopyTo1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle array, int index) {
            // (Lsystem/Array;I)V
            // (LSystem/Array;I)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Collections.ArrayList @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Collections.ArrayList>(@__env, @__obj);
            ((global::System.Collections.ICollection)(@__real)).CopyTo(global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Array>(@__env, array), index);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static int Count2(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()I
            // ()I
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            int @__return = default(int);
            try {
            global::System.Collections.ArrayList @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Collections.ArrayList>(@__env, @__obj);
            @__return = ((int)(((global::System.Collections.ICollection)(@__real)).Count));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle SyncRoot3(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Lsystem/Object;
            // ()LSystem/Object;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::System.Collections.ArrayList @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Collections.ArrayList>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<object>(@__env, ((global::System.Collections.ICollection)(@__real)).SyncRoot);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static bool IsSynchronized4(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Z
            // ()Z
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            bool @__return = default(bool);
            try {
            global::System.Collections.ArrayList @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Collections.ArrayList>(@__env, @__obj);
            @__return = ((bool)(((global::System.Collections.ICollection)(@__real)).IsSynchronized));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Item5(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int index) {
            // (I)Lsystem/Object;
            // (I)LSystem/Object;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::System.Collections.ArrayList @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Collections.ArrayList>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<object>(@__env, ((global::System.Collections.IList)(@__real))[index]);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void Item6(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int index, global::net.sf.jni4net.utils.JniLocalHandle value) {
            // (ILsystem/Object;)V
            // (ILSystem/Object;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Collections.ArrayList @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Collections.ArrayList>(@__env, @__obj);
            ((global::System.Collections.IList)(@__real))[index] = global::net.sf.jni4net.utils.Convertor.FullJ2C<object>(@__env, value);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static int Add7(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle value) {
            // (Lsystem/Object;)I
            // (LSystem/Object;)I
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            int @__return = default(int);
            try {
            global::System.Collections.ArrayList @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Collections.ArrayList>(@__env, @__obj);
            @__return = ((int)(((global::System.Collections.IList)(@__real)).Add(global::net.sf.jni4net.utils.Convertor.FullJ2C<object>(@__env, value))));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static bool Contains8(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle value) {
            // (Lsystem/Object;)Z
            // (LSystem/Object;)Z
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            bool @__return = default(bool);
            try {
            global::System.Collections.ArrayList @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Collections.ArrayList>(@__env, @__obj);
            @__return = ((bool)(((global::System.Collections.IList)(@__real)).Contains(global::net.sf.jni4net.utils.Convertor.FullJ2C<object>(@__env, value))));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void Clear9(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Collections.ArrayList @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Collections.ArrayList>(@__env, @__obj);
            ((global::System.Collections.IList)(@__real)).Clear();
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static bool IsReadOnly10(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Z
            // ()Z
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            bool @__return = default(bool);
            try {
            global::System.Collections.ArrayList @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Collections.ArrayList>(@__env, @__obj);
            @__return = ((bool)(((global::System.Collections.IList)(@__real)).IsReadOnly));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static bool IsFixedSize11(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Z
            // ()Z
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            bool @__return = default(bool);
            try {
            global::System.Collections.ArrayList @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Collections.ArrayList>(@__env, @__obj);
            @__return = ((bool)(((global::System.Collections.IList)(@__real)).IsFixedSize));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static int IndexOf12(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle value) {
            // (Lsystem/Object;)I
            // (LSystem/Object;)I
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            int @__return = default(int);
            try {
            global::System.Collections.ArrayList @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Collections.ArrayList>(@__env, @__obj);
            @__return = ((int)(((global::System.Collections.IList)(@__real)).IndexOf(global::net.sf.jni4net.utils.Convertor.FullJ2C<object>(@__env, value))));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void Insert13(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int index, global::net.sf.jni4net.utils.JniLocalHandle value) {
            // (ILsystem/Object;)V
            // (ILSystem/Object;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Collections.ArrayList @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Collections.ArrayList>(@__env, @__obj);
            ((global::System.Collections.IList)(@__real)).Insert(index, global::net.sf.jni4net.utils.Convertor.FullJ2C<object>(@__env, value));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void Remove14(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle value) {
            // (Lsystem/Object;)V
            // (LSystem/Object;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Collections.ArrayList @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Collections.ArrayList>(@__env, @__obj);
            ((global::System.Collections.IList)(@__real)).Remove(global::net.sf.jni4net.utils.Convertor.FullJ2C<object>(@__env, value));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void RemoveAt15(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int index) {
            // (I)V
            // (I)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Collections.ArrayList @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Collections.ArrayList>(@__env, @__obj);
            ((global::System.Collections.IList)(@__real)).RemoveAt(index);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Clone16(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()Lsystem/Object;
            // ()LSystem/Object;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::System.Collections.ArrayList @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Collections.ArrayList>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<object>(@__env, ((global::System.ICloneable)(@__real)).Clone());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static int Capacity17(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()I
            // ()I
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            int @__return = default(int);
            try {
            global::System.Collections.ArrayList @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Collections.ArrayList>(@__env, @__obj);
            @__return = ((int)(@__real.Capacity));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void Capacity18(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int value) {
            // (I)V
            // (I)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Collections.ArrayList @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Collections.ArrayList>(@__env, @__obj);
            @__real.Capacity = value;
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Adapter19(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle list) {
            // (Lsystem/collections/IList;)Lsystem/collections/ArrayList;
            // (LSystem/Collections/IList;)LSystem/Collections/ArrayList;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.Collections.ArrayList>(@__env, global::System.Collections.ArrayList.Adapter(global::net.sf.jni4net.utils.Convertor.FullJ2C<global::System.Collections.IList>(@__env, list)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void AddRange20(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle c) {
            // (Lsystem/collections/ICollection;)V
            // (LSystem/Collections/ICollection;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Collections.ArrayList @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Collections.ArrayList>(@__env, @__obj);
            @__real.AddRange(global::net.sf.jni4net.utils.Convertor.FullJ2C<global::System.Collections.ICollection>(@__env, c));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static int BinarySearch21(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int index, int count, global::net.sf.jni4net.utils.JniLocalHandle value, global::net.sf.jni4net.utils.JniLocalHandle comparer) {
            // (IILsystem/Object;Lsystem/Object;)I
            // (IILSystem/Object;LSystem/Collections/IComparer;)I
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            int @__return = default(int);
            try {
            global::System.Collections.ArrayList @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Collections.ArrayList>(@__env, @__obj);
            @__return = ((int)(@__real.BinarySearch(index, count, global::net.sf.jni4net.utils.Convertor.FullJ2C<object>(@__env, value), global::net.sf.jni4net.utils.Convertor.FullJ2C<global::System.Collections.IComparer>(@__env, comparer))));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static int BinarySearch22(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle value) {
            // (Lsystem/Object;)I
            // (LSystem/Object;)I
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            int @__return = default(int);
            try {
            global::System.Collections.ArrayList @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Collections.ArrayList>(@__env, @__obj);
            @__return = ((int)(@__real.BinarySearch(global::net.sf.jni4net.utils.Convertor.FullJ2C<object>(@__env, value))));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static int BinarySearch23(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle value, global::net.sf.jni4net.utils.JniLocalHandle comparer) {
            // (Lsystem/Object;Lsystem/Object;)I
            // (LSystem/Object;LSystem/Collections/IComparer;)I
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            int @__return = default(int);
            try {
            global::System.Collections.ArrayList @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Collections.ArrayList>(@__env, @__obj);
            @__return = ((int)(@__real.BinarySearch(global::net.sf.jni4net.utils.Convertor.FullJ2C<object>(@__env, value), global::net.sf.jni4net.utils.Convertor.FullJ2C<global::System.Collections.IComparer>(@__env, comparer))));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void CopyTo24(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle array) {
            // (Lsystem/Array;)V
            // (LSystem/Array;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Collections.ArrayList @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Collections.ArrayList>(@__env, @__obj);
            @__real.CopyTo(global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Array>(@__env, array));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void CopyTo25(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int index, global::net.sf.jni4net.utils.JniLocalHandle array, int arrayIndex, int count) {
            // (ILsystem/Array;II)V
            // (ILSystem/Array;II)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Collections.ArrayList @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Collections.ArrayList>(@__env, @__obj);
            @__real.CopyTo(index, global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Array>(@__env, array), arrayIndex, count);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle FixedSize26(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle list) {
            // (Lsystem/collections/IList;)Lsystem/collections/IList;
            // (LSystem/Collections/IList;)LSystem/Collections/IList;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<global::System.Collections.IList>(@__env, global::System.Collections.ArrayList.FixedSize(global::net.sf.jni4net.utils.Convertor.FullJ2C<global::System.Collections.IList>(@__env, list)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle FixedSize27(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle list) {
            // (Lsystem/collections/ArrayList;)Lsystem/collections/ArrayList;
            // (LSystem/Collections/ArrayList;)LSystem/Collections/ArrayList;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.Collections.ArrayList>(@__env, global::System.Collections.ArrayList.FixedSize(global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Collections.ArrayList>(@__env, list)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle GetEnumerator28(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int index, int count) {
            // (II)Lsystem/collections/IEnumerator;
            // (II)LSystem/Collections/IEnumerator;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::System.Collections.ArrayList @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Collections.ArrayList>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<global::System.Collections.IEnumerator>(@__env, @__real.GetEnumerator(index, count));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static int IndexOf29(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle value, int startIndex) {
            // (Lsystem/Object;I)I
            // (LSystem/Object;I)I
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            int @__return = default(int);
            try {
            global::System.Collections.ArrayList @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Collections.ArrayList>(@__env, @__obj);
            @__return = ((int)(@__real.IndexOf(global::net.sf.jni4net.utils.Convertor.FullJ2C<object>(@__env, value), startIndex)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static int IndexOf30(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle value, int startIndex, int count) {
            // (Lsystem/Object;II)I
            // (LSystem/Object;II)I
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            int @__return = default(int);
            try {
            global::System.Collections.ArrayList @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Collections.ArrayList>(@__env, @__obj);
            @__return = ((int)(@__real.IndexOf(global::net.sf.jni4net.utils.Convertor.FullJ2C<object>(@__env, value), startIndex, count)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void InsertRange31(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int index, global::net.sf.jni4net.utils.JniLocalHandle c) {
            // (ILsystem/collections/ICollection;)V
            // (ILSystem/Collections/ICollection;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Collections.ArrayList @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Collections.ArrayList>(@__env, @__obj);
            @__real.InsertRange(index, global::net.sf.jni4net.utils.Convertor.FullJ2C<global::System.Collections.ICollection>(@__env, c));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static int LastIndexOf32(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle value) {
            // (Lsystem/Object;)I
            // (LSystem/Object;)I
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            int @__return = default(int);
            try {
            global::System.Collections.ArrayList @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Collections.ArrayList>(@__env, @__obj);
            @__return = ((int)(@__real.LastIndexOf(global::net.sf.jni4net.utils.Convertor.FullJ2C<object>(@__env, value))));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static int LastIndexOf33(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle value, int startIndex) {
            // (Lsystem/Object;I)I
            // (LSystem/Object;I)I
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            int @__return = default(int);
            try {
            global::System.Collections.ArrayList @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Collections.ArrayList>(@__env, @__obj);
            @__return = ((int)(@__real.LastIndexOf(global::net.sf.jni4net.utils.Convertor.FullJ2C<object>(@__env, value), startIndex)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static int LastIndexOf34(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle value, int startIndex, int count) {
            // (Lsystem/Object;II)I
            // (LSystem/Object;II)I
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            int @__return = default(int);
            try {
            global::System.Collections.ArrayList @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Collections.ArrayList>(@__env, @__obj);
            @__return = ((int)(@__real.LastIndexOf(global::net.sf.jni4net.utils.Convertor.FullJ2C<object>(@__env, value), startIndex, count)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle ReadOnly35(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle list) {
            // (Lsystem/collections/IList;)Lsystem/collections/IList;
            // (LSystem/Collections/IList;)LSystem/Collections/IList;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<global::System.Collections.IList>(@__env, global::System.Collections.ArrayList.ReadOnly(global::net.sf.jni4net.utils.Convertor.FullJ2C<global::System.Collections.IList>(@__env, list)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle ReadOnly36(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle list) {
            // (Lsystem/collections/ArrayList;)Lsystem/collections/ArrayList;
            // (LSystem/Collections/ArrayList;)LSystem/Collections/ArrayList;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.Collections.ArrayList>(@__env, global::System.Collections.ArrayList.ReadOnly(global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Collections.ArrayList>(@__env, list)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void RemoveRange37(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int index, int count) {
            // (II)V
            // (II)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Collections.ArrayList @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Collections.ArrayList>(@__env, @__obj);
            @__real.RemoveRange(index, count);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Repeat38(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle value, int count) {
            // (Lsystem/Object;I)Lsystem/collections/ArrayList;
            // (LSystem/Object;I)LSystem/Collections/ArrayList;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.Collections.ArrayList>(@__env, global::System.Collections.ArrayList.Repeat(global::net.sf.jni4net.utils.Convertor.FullJ2C<object>(@__env, value), count));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void Reverse39(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Collections.ArrayList @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Collections.ArrayList>(@__env, @__obj);
            @__real.Reverse();
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void Reverse40(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int index, int count) {
            // (II)V
            // (II)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Collections.ArrayList @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Collections.ArrayList>(@__env, @__obj);
            @__real.Reverse(index, count);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void SetRange41(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int index, global::net.sf.jni4net.utils.JniLocalHandle c) {
            // (ILsystem/collections/ICollection;)V
            // (ILSystem/Collections/ICollection;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Collections.ArrayList @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Collections.ArrayList>(@__env, @__obj);
            @__real.SetRange(index, global::net.sf.jni4net.utils.Convertor.FullJ2C<global::System.Collections.ICollection>(@__env, c));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle GetRange42(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int index, int count) {
            // (II)Lsystem/collections/ArrayList;
            // (II)LSystem/Collections/ArrayList;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::System.Collections.ArrayList @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Collections.ArrayList>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.Collections.ArrayList>(@__env, @__real.GetRange(index, count));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void Sort43(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Collections.ArrayList @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Collections.ArrayList>(@__env, @__obj);
            @__real.Sort();
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void Sort44(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle comparer) {
            // (Lsystem/Object;)V
            // (LSystem/Collections/IComparer;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Collections.ArrayList @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Collections.ArrayList>(@__env, @__obj);
            @__real.Sort(global::net.sf.jni4net.utils.Convertor.FullJ2C<global::System.Collections.IComparer>(@__env, comparer));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void Sort45(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int index, int count, global::net.sf.jni4net.utils.JniLocalHandle comparer) {
            // (IILsystem/Object;)V
            // (IILSystem/Collections/IComparer;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Collections.ArrayList @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Collections.ArrayList>(@__env, @__obj);
            @__real.Sort(index, count, global::net.sf.jni4net.utils.Convertor.FullJ2C<global::System.Collections.IComparer>(@__env, comparer));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Synchronized46(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle list) {
            // (Lsystem/collections/IList;)Lsystem/collections/IList;
            // (LSystem/Collections/IList;)LSystem/Collections/IList;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            @__return = global::net.sf.jni4net.utils.Convertor.FullC2J<global::System.Collections.IList>(@__env, global::System.Collections.ArrayList.Synchronized(global::net.sf.jni4net.utils.Convertor.FullJ2C<global::System.Collections.IList>(@__env, list)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle Synchronized47(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle list) {
            // (Lsystem/collections/ArrayList;)Lsystem/collections/ArrayList;
            // (LSystem/Collections/ArrayList;)LSystem/Collections/ArrayList;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.Collections.ArrayList>(@__env, global::System.Collections.ArrayList.Synchronized(global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Collections.ArrayList>(@__env, list)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle ToArray48(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()[Lsystem/Object;
            // ()[LSystem/Object;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::System.Collections.ArrayList @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Collections.ArrayList>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.ArrayFullC2J<object[], object>(@__env, @__real.ToArray());
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static global::net.sf.jni4net.utils.JniHandle ToArray49(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle type) {
            // (Lsystem/Type;)Lsystem/Array;
            // (LSystem/Type;)LSystem/Array;
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            global::net.sf.jni4net.utils.JniHandle @__return = default(global::net.sf.jni4net.utils.JniHandle);
            try {
            global::System.Collections.ArrayList @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Collections.ArrayList>(@__env, @__obj);
            @__return = global::net.sf.jni4net.utils.Convertor.StrongC2Jp<global::System.Array>(@__env, @__real.ToArray(global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Type>(@__env, type)));
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
            return @__return;
        }
        
        private static void TrimToSize50(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Collections.ArrayList @__real = global::net.sf.jni4net.utils.Convertor.StrongJp2C<global::System.Collections.ArrayList>(@__env, @__obj);
            @__real.TrimToSize();
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void @__ctorArrayList0(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle @__obj) {
            // ()V
            // ()V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Collections.ArrayList @__real = new global::System.Collections.ArrayList();
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void @__ctorArrayList1(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle @__obj, int capacity) {
            // (I)V
            // (I)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Collections.ArrayList @__real = new global::System.Collections.ArrayList(capacity);
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        private static void @__ctorArrayList2(global::System.IntPtr @__envp, global::net.sf.jni4net.utils.JniLocalHandle @__class, global::net.sf.jni4net.utils.JniLocalHandle @__obj, global::net.sf.jni4net.utils.JniLocalHandle c) {
            // (Lsystem/collections/ICollection;)V
            // (LSystem/Collections/ICollection;)V
            global::net.sf.jni4net.jni.JNIEnv @__env = global::net.sf.jni4net.jni.JNIEnv.Wrap(@__envp);
            try {
            global::System.Collections.ArrayList @__real = new global::System.Collections.ArrayList(global::net.sf.jni4net.utils.Convertor.FullJ2C<global::System.Collections.ICollection>(@__env, c));
            global::net.sf.jni4net.utils.Convertor.InitProxy(@__env, @__obj, @__real);
            }catch (global::System.Exception __ex){@__env.ThrowExisting(__ex);}
        }
        
        new internal sealed class ContructionHelper : global::net.sf.jni4net.utils.IConstructionHelper {
            
            public global::net.sf.jni4net.jni.IJvmProxy CreateProxy(global::net.sf.jni4net.jni.JNIEnv @__env) {
                return new global::System.Collections.@__ArrayList(@__env);
            }
        }
    }
    #endregion
}
